# GitHub action to test arduino sketch compiles

name: Arduino Sketch Compiles

# Trigger workflow when post-install-setup.sh changes
on:
  push:
    branches: [ main ]
    # paths:
    #   - 'arduino-uno/arduino/**'

#
jobs:
  # one job
  run-arduino-sketch-compile-test:
    # run on ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # install arduino cli
      - name: Install arduino-cli
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh

      # install arduino board
      - name: Install arduino-cli cores
        run: |
          ./bin/arduino-cli core install arduino:avr
          ./bin/arduino-cli core update-index
          ./bin/arduino-cli core list

      # compile sketch
      - name: Compile sketch
        run: ./bin/arduino-cli compile --fqbn arduino:avr:uno arduino-uno/arduino/tmp36-temperature-sensor
